package com.niquewrld.casino.googlesignin

import android.app.Activity
import android.util.Log
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.GetCredentialResponse
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import org.godotengine.godot.Godot
import org.godotengine.godot.plugin.GodotPlugin
import org.godotengine.godot.plugin.SignalInfo
import org.godotengine.godot.plugin.UsedByGodot
import java.security.MessageDigest
import java.util.UUID

/**
 * Godot Android Plugin for Google Sign-In using Credential Manager API
 */
class GodotGoogleSignIn(godot: Godot) : GodotPlugin(godot) {
    
    companion object {
        private const val TAG = "GodotGoogleSignIn"
    }
    
    private var credentialManager: CredentialManager? = null
    private var webClientId: String = ""
    private val coroutineScope = CoroutineScope(Dispatchers.Main)
    
    // Signals
    private val signInSuccessSignal = SignalInfo("sign_in_success", String::class.java, String::class.java, String::class.java)
    private val signInFailedSignal = SignalInfo("sign_in_failed", String::class.java)
    private val silentSignInFailedSignal = SignalInfo("silent_sign_in_failed", String::class.java)
    private val signOutCompleteSignal = SignalInfo("sign_out_complete")

    override fun getPluginName(): String = "GodotGoogleSignIn"

    override fun getPluginSignals(): Set<SignalInfo> {
        return setOf(signInSuccessSignal, signInFailedSignal, silentSignInFailedSignal, signOutCompleteSignal)
    }
    
    private fun getOrCreateCredentialManager(): CredentialManager? {
        if (credentialManager == null) {
            val act = activity
            if (act != null) {
                credentialManager = CredentialManager.create(act)
                Log.d(TAG, "CredentialManager created")
            }
        }
        return credentialManager
    }
    
    /**
     * Initialize the plugin with your Web Client ID from Google Cloud Console
     */
    @UsedByGodot
    fun initialize(webClientId: String) {
        this.webClientId = webClientId
        Log.d(TAG, "Initialized with Web Client ID")
    }
    
    /**
     * Check if the plugin is properly initialized
     */
    @UsedByGodot
    fun isInitialized(): Boolean {
        return webClientId.isNotEmpty()
    }
    
    /**
     * Start Google Sign-In flow
     * This will show the Google Sign-In bottom sheet
     */
    @UsedByGodot
    fun signIn() {
        signInInternal(null)
    }

    /**
     * Start Google Sign-In flow with a caller-supplied raw nonce.
     *
     * Use this variant when your app needs to verify the ID token on a backend
     * (e.g. Supabase, Firebase, or a custom OIDC server).  The caller generates
     * a cryptographically random raw nonce, passes it here, and later sends that
     * same raw nonce to the backend alongside the ID token.  The plugin will
     * SHA-256 hash the raw nonce before passing it to Google; Google embeds the
     * hash in the ID token's `nonce` claim, allowing the backend to verify it.
     *
     * @param rawNonce The raw (unhashed) nonce string generated by the caller.
     */
    @UsedByGodot
    fun signInWithNonce(rawNonce: String) {
        signInInternal(rawNonce)
    }

    /**
     * Attempt a silent (non-interactive) sign-in using a previously authorized account.
     *
     * Uses `setFilterByAuthorizedAccounts(true)` + `setAutoSelectEnabled(true)` so the
     * Credential Manager resolves without showing any UI.  If no single authorized account
     * can be resolved automatically, the request fails immediately and the
     * `silent_sign_in_failed` signal is emitted — no account picker is ever shown.
     * On success the normal `sign_in_success` signal is emitted.
     */
    @UsedByGodot
    fun silentSignIn() {
        signInInternal(null, silent = true)
    }

    /**
     * Attempt a silent sign-in with a caller-supplied raw nonce.
     * See [silentSignIn] for the silent flow and [signInWithNonce] for nonce details.
     *
     * @param rawNonce The raw (unhashed) nonce string generated by the caller.
     */
    @UsedByGodot
    fun silentSignInWithNonce(rawNonce: String) {
        signInInternal(rawNonce, silent = true)
    }

    private fun signInInternal(rawNonce: String?, silent: Boolean = false) {
        if (webClientId.isEmpty()) {
            emitSignal(signInFailedSignal.name, "Plugin not initialized. Call initialize() first.")
            return
        }
        
        val act = activity ?: run {
            emitSignal(signInFailedSignal.name, "Activity not available")
            return
        }
        
        val cm = getOrCreateCredentialManager() ?: run {
            emitSignal(signInFailedSignal.name, "CredentialManager not available")
            return
        }

        coroutineScope.launch {
            try {
                val nonce = if (rawNonce != null) hashNonce(rawNonce) else generateNonce()

                // Try to sign in with existing authorized account first
                val googleIdOption = GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(true)
                    .setServerClientId(webClientId)
                    .setAutoSelectEnabled(true)
                    .setNonce(nonce)
                    .build()

                val request = GetCredentialRequest.Builder()
                    .addCredentialOption(googleIdOption)
                    .build()

                try {
                    val result = cm.getCredential(act, request)
                    handleSignInResult(result)
                } catch (e: GetCredentialException) {
                    if (silent) {
                        // Silent mode: never show UI — report failure immediately.
                        Log.d(TAG, "Silent sign-in failed (no auto-selectable account): ${e.message}")
                        emitSignal(silentSignInFailedSignal.name, e.message ?: "No authorized account available")
                    } else {
                        // Interactive mode: fall back to full account chooser.
                        Log.d(TAG, "No authorized accounts, trying with all accounts")
                        signInWithAllAccounts(act, nonce, cm)
                    }
                }
            } catch (e: Exception) {
                Log.e(TAG, "Sign-in failed", e)
                emitSignal(signInFailedSignal.name, e.message ?: "Unknown error")
            }
        }
    }
    
    /**
     * Sign in allowing user to choose from all Google accounts
     */
    @UsedByGodot
    fun signInWithAccountChooser() {
        signInWithAccountChooserInternal(null)
    }

    /**
     * Sign in with account chooser and a caller-supplied raw nonce.
     * See [signInWithNonce] for details on the nonce flow.
     *
     * @param rawNonce The raw (unhashed) nonce string generated by the caller.
     */
    @UsedByGodot
    fun signInWithAccountChooserWithNonce(rawNonce: String) {
        signInWithAccountChooserInternal(rawNonce)
    }

    private fun signInWithAccountChooserInternal(rawNonce: String?) {
        if (webClientId.isEmpty()) {
            emitSignal(signInFailedSignal.name, "Plugin not initialized. Call initialize() first.")
            return
        }
        
        val act = activity ?: run {
            emitSignal(signInFailedSignal.name, "Activity not available")
            return
        }
        
        val cm = getOrCreateCredentialManager() ?: run {
            emitSignal(signInFailedSignal.name, "CredentialManager not available")
            return
        }
        
        coroutineScope.launch {
            try {
                val nonce = if (rawNonce != null) hashNonce(rawNonce) else generateNonce()
                signInWithAllAccounts(act, nonce, cm)
            } catch (e: Exception) {
                Log.e(TAG, "Sign-in failed", e)
                emitSignal(signInFailedSignal.name, e.message ?: "Unknown error")
            }
        }
    }
    
    /**
     * Use the Sign in with Google button flow
     */
    @UsedByGodot
    fun signInWithGoogleButton() {
        signInWithGoogleButtonInternal(null)
    }

    /**
     * Sign in with the Google button flow and a caller-supplied raw nonce.
     * See [signInWithNonce] for details on the nonce flow.
     *
     * @param rawNonce The raw (unhashed) nonce string generated by the caller.
     */
    @UsedByGodot
    fun signInWithGoogleButtonWithNonce(rawNonce: String) {
        signInWithGoogleButtonInternal(rawNonce)
    }

    private fun signInWithGoogleButtonInternal(rawNonce: String?) {
        if (webClientId.isEmpty()) {
            emitSignal(signInFailedSignal.name, "Plugin not initialized. Call initialize() first.")
            return
        }
        
        val act = activity ?: run {
            emitSignal(signInFailedSignal.name, "Activity not available")
            return
        }
        
        val cm = getOrCreateCredentialManager() ?: run {
            emitSignal(signInFailedSignal.name, "CredentialManager not available")
            return
        }
        
        coroutineScope.launch {
            try {
                val nonce = if (rawNonce != null) hashNonce(rawNonce) else generateNonce()

                val signInWithGoogleOption = GetSignInWithGoogleOption.Builder(webClientId)
                    .setNonce(nonce)
                    .build()
                
                val request = GetCredentialRequest.Builder()
                    .addCredentialOption(signInWithGoogleOption)
                    .build()
                
                val result = cm.getCredential(act, request)
                handleSignInResult(result)
            } catch (e: GetCredentialException) {
                Log.e(TAG, "Sign-in with Google button failed", e)
                emitSignal(signInFailedSignal.name, e.message ?: "Sign-in cancelled")
            } catch (e: Exception) {
                Log.e(TAG, "Sign-in failed", e)
                emitSignal(signInFailedSignal.name, e.message ?: "Unknown error")
            }
        }
    }
    
    private suspend fun signInWithAllAccounts(activity: Activity, nonce: String, cm: CredentialManager) {
        val googleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(webClientId)
            .setNonce(nonce)
            .build()
        
        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()
        
        try {
            val result = cm.getCredential(activity, request)
            handleSignInResult(result)
        } catch (e: GetCredentialException) {
            Log.e(TAG, "Sign-in with all accounts failed", e)
            emitSignal(signInFailedSignal.name, e.message ?: "Sign-in cancelled")
        }
    }
    
    private fun handleSignInResult(result: GetCredentialResponse) {
        val credential = result.credential
        
        when (credential) {
            is CustomCredential -> {
                if (credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                    try {
                        val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                        
                        val idToken = googleIdTokenCredential.idToken
                        val email = googleIdTokenCredential.id
                        val displayName = googleIdTokenCredential.displayName ?: ""
                        
                        Log.d(TAG, "Sign-in successful: $email")
                        
                        // Emit success signal with ID token, email, and display name
                        emitSignal(signInSuccessSignal.name, idToken, email, displayName)
                    } catch (e: GoogleIdTokenParsingException) {
                        Log.e(TAG, "Invalid Google ID token", e)
                        emitSignal(signInFailedSignal.name, "Invalid Google ID token")
                    }
                } else {
                    Log.e(TAG, "Unexpected credential type: ${credential.type}")
                    emitSignal(signInFailedSignal.name, "Unexpected credential type")
                }
            }
            else -> {
                Log.e(TAG, "Unexpected credential class: ${credential::class.java.name}")
                emitSignal(signInFailedSignal.name, "Unexpected credential type")
            }
        }
    }
    
    /**
     * Sign out and clear credential state
     */
    @UsedByGodot
    fun signOut() {
        val cm = getOrCreateCredentialManager()
        coroutineScope.launch {
            try {
                cm?.clearCredentialState(ClearCredentialStateRequest())
                Log.d(TAG, "Sign-out complete")
                emitSignal(signOutCompleteSignal.name)
            } catch (e: Exception) {
                Log.e(TAG, "Sign-out failed", e)
                // Still emit complete since local state should be cleared
                emitSignal(signOutCompleteSignal.name)
            }
        }
    }
    
    /**
     * Generate a random nonce and return its SHA-256 hex hash.
     */
    private fun generateNonce(): String = hashNonce(UUID.randomUUID().toString())

    /**
     * SHA-256 hash a raw nonce string, returning a lowercase hex string.
     * This is what gets passed to Google; the caller retains the raw value for
     * backend verification.
     */
    private fun hashNonce(rawNonce: String): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(rawNonce.toByteArray(Charsets.UTF_8))
        return digest.fold("") { str, it -> str + "%02x".format(it) }
    }
}
